version: '2'

services:
  base:
    build: .

  api:
    extends: base
    entrypoint: apistar
    command: ["run", "--host", "0.0.0.0", "--port", "8000"]
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - "./api:/app"